version: "3.9"

services:
  go-timeslot-app:
    container_name: go-timeslot-app
    image: wizkaley/go-timeslot-app:5.0.4
    build: .
    environment:
      - host=go_db
      - user=postgres
      - password=postgres
      - dbname=postgres
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
